---
- name: Configure jenkins with maven
  hosts: jenkins-slave
  become: true

  tasks:
  - name: Update ubuntu and cache
    ansible.builtin.apt:
      update_cache: true

  - name: Install Java
    ansible.builtin.apt:
      name: openjdk-17-jre
      state: present

  - name: Download maven package
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      dest: /home/ubuntu
      state: present
  
  - name: Extract maven
    ansible.builtin.unarchive:
      src: apache-maven-3.9.4-bin.tar.gz
      dest: /home/ubuntu
      remote_src: yes